/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gongmh.gen_java;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum enumType implements org.apache.thrift.TEnum {
  FIRST(0),
  SECOND(1);

  private final int value;

  private enumType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static enumType findByValue(int value) { 
    switch (value) {
      case 0:
        return FIRST;
      case 1:
        return SECOND;
      default:
        return null;
    }
  }
}
