/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gongmh.gen_java;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class struceType implements org.apache.thrift.TBase<struceType, struceType._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("struceType");

  private static final org.apache.thrift.protocol.TField ONE_FIELD_DESC = new org.apache.thrift.protocol.TField("one", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField TWO_FIELD_DESC = new org.apache.thrift.protocol.TField("two", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField THREE_FIELD_DESC = new org.apache.thrift.protocol.TField("three", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new struceTypeStandardSchemeFactory());
    schemes.put(TupleScheme.class, new struceTypeTupleSchemeFactory());
  }

  public int one; // required
  public long two; // required
  public String three; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ONE((short)1, "one"),
    TWO((short)2, "two"),
    THREE((short)3, "three");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ONE
          return ONE;
        case 2: // TWO
          return TWO;
        case 3: // THREE
          return THREE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ONE_ISSET_ID = 0;
  private static final int __TWO_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.THREE};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ONE, new org.apache.thrift.meta_data.FieldMetaData("one", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TWO, new org.apache.thrift.meta_data.FieldMetaData("two", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.THREE, new org.apache.thrift.meta_data.FieldMetaData("three", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(struceType.class, metaDataMap);
  }

  public struceType() {
  }

  public struceType(
    int one,
    long two)
  {
    this();
    this.one = one;
    setOneIsSet(true);
    this.two = two;
    setTwoIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public struceType(struceType other) {
    __isset_bitfield = other.__isset_bitfield;
    this.one = other.one;
    this.two = other.two;
    if (other.isSetThree()) {
      this.three = other.three;
    }
  }

  public struceType deepCopy() {
    return new struceType(this);
  }

  @Override
  public void clear() {
    setOneIsSet(false);
    this.one = 0;
    setTwoIsSet(false);
    this.two = 0;
    this.three = null;
  }

  public int getOne() {
    return this.one;
  }

  public struceType setOne(int one) {
    this.one = one;
    setOneIsSet(true);
    return this;
  }

  public void unsetOne() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ONE_ISSET_ID);
  }

  /** Returns true if field one is set (has been assigned a value) and false otherwise */
  public boolean isSetOne() {
    return EncodingUtils.testBit(__isset_bitfield, __ONE_ISSET_ID);
  }

  public void setOneIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ONE_ISSET_ID, value);
  }

  public long getTwo() {
    return this.two;
  }

  public struceType setTwo(long two) {
    this.two = two;
    setTwoIsSet(true);
    return this;
  }

  public void unsetTwo() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TWO_ISSET_ID);
  }

  /** Returns true if field two is set (has been assigned a value) and false otherwise */
  public boolean isSetTwo() {
    return EncodingUtils.testBit(__isset_bitfield, __TWO_ISSET_ID);
  }

  public void setTwoIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TWO_ISSET_ID, value);
  }

  public String getThree() {
    return this.three;
  }

  public struceType setThree(String three) {
    this.three = three;
    return this;
  }

  public void unsetThree() {
    this.three = null;
  }

  /** Returns true if field three is set (has been assigned a value) and false otherwise */
  public boolean isSetThree() {
    return this.three != null;
  }

  public void setThreeIsSet(boolean value) {
    if (!value) {
      this.three = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ONE:
      if (value == null) {
        unsetOne();
      } else {
        setOne((Integer)value);
      }
      break;

    case TWO:
      if (value == null) {
        unsetTwo();
      } else {
        setTwo((Long)value);
      }
      break;

    case THREE:
      if (value == null) {
        unsetThree();
      } else {
        setThree((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ONE:
      return Integer.valueOf(getOne());

    case TWO:
      return Long.valueOf(getTwo());

    case THREE:
      return getThree();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ONE:
      return isSetOne();
    case TWO:
      return isSetTwo();
    case THREE:
      return isSetThree();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof struceType)
      return this.equals((struceType)that);
    return false;
  }

  public boolean equals(struceType that) {
    if (that == null)
      return false;

    boolean this_present_one = true;
    boolean that_present_one = true;
    if (this_present_one || that_present_one) {
      if (!(this_present_one && that_present_one))
        return false;
      if (this.one != that.one)
        return false;
    }

    boolean this_present_two = true;
    boolean that_present_two = true;
    if (this_present_two || that_present_two) {
      if (!(this_present_two && that_present_two))
        return false;
      if (this.two != that.two)
        return false;
    }

    boolean this_present_three = true && this.isSetThree();
    boolean that_present_three = true && that.isSetThree();
    if (this_present_three || that_present_three) {
      if (!(this_present_three && that_present_three))
        return false;
      if (!this.three.equals(that.three))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(struceType other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    struceType typedOther = (struceType)other;

    lastComparison = Boolean.valueOf(isSetOne()).compareTo(typedOther.isSetOne());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOne()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.one, typedOther.one);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTwo()).compareTo(typedOther.isSetTwo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTwo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.two, typedOther.two);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetThree()).compareTo(typedOther.isSetThree());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetThree()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.three, typedOther.three);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("struceType(");
    boolean first = true;

    sb.append("one:");
    sb.append(this.one);
    first = false;
    if (!first) sb.append(", ");
    sb.append("two:");
    sb.append(this.two);
    first = false;
    if (isSetThree()) {
      if (!first) sb.append(", ");
      sb.append("three:");
      if (this.three == null) {
        sb.append("null");
      } else {
        sb.append(this.three);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'one' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'two' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class struceTypeStandardSchemeFactory implements SchemeFactory {
    public struceTypeStandardScheme getScheme() {
      return new struceTypeStandardScheme();
    }
  }

  private static class struceTypeStandardScheme extends StandardScheme<struceType> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, struceType struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ONE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.one = iprot.readI32();
              struct.setOneIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TWO
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.two = iprot.readI64();
              struct.setTwoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // THREE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.three = iprot.readString();
              struct.setThreeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetOne()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'one' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetTwo()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'two' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, struceType struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ONE_FIELD_DESC);
      oprot.writeI32(struct.one);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(TWO_FIELD_DESC);
      oprot.writeI64(struct.two);
      oprot.writeFieldEnd();
      if (struct.three != null) {
        if (struct.isSetThree()) {
          oprot.writeFieldBegin(THREE_FIELD_DESC);
          oprot.writeString(struct.three);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class struceTypeTupleSchemeFactory implements SchemeFactory {
    public struceTypeTupleScheme getScheme() {
      return new struceTypeTupleScheme();
    }
  }

  private static class struceTypeTupleScheme extends TupleScheme<struceType> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, struceType struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.one);
      oprot.writeI64(struct.two);
      BitSet optionals = new BitSet();
      if (struct.isSetThree()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetThree()) {
        oprot.writeString(struct.three);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, struceType struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.one = iprot.readI32();
      struct.setOneIsSet(true);
      struct.two = iprot.readI64();
      struct.setTwoIsSet(true);
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.three = iprot.readString();
        struct.setThreeIsSet(true);
      }
    }
  }

}

